### ISSUE TITLE
ODM and embedded documents

### ISSUE THREAD

**Issue by j** [TheFootballSocialClub/FSCHateoasBundle#20]
I'm using ODM, and it's automatically adding links to all my embedded documents... Is there a way to only show HATEOAS stuff when configured to do so instead on all serialized stuff?

**Comment by baldurrensch** [comment]
You mean empty `links` and `embedded`?

**Comment by adrienbrault** [comment]
@jstout24 Can you confirm that https://github.com/TheFootballSocialClub/FSCHateoasBundle/commit/e27749bb9df534d48ddd6232e84ca4d1ba1c6811 fixes your issue ?

**Comment by j** [comment]
Yep, it does... Except, in XML.  You forgot to add it on onPostSerializeXML method.

**Comment by adrienbrault** [comment]
Shouldn't change anything in XML.
