### ISSUE TITLE
Problem with Relation

### ISSUE THREAD

**Issue by baldurrensch** [TheFootballSocialClub/FSCHateoasBundle#5]
I am trying to get the bundle working, but the relations are not working. I tried it both with master, as well as with thdev-formview-serialization branch. Here is the interesting part of my code: https://gist.github.com/3961294. 

Basically, The links just don't show up. I have traced it to https://github.com/TheFootballSocialClub/FSCHateoasBundle/blob/master/Factory/LinkFactory.php#L34 where the class metadata is empty. This is where I am stuck. 

Help, please. Thanks.

**Comment by adrienbrault** [comment]
Fixed in ce653c364c8461af1f232984fef24ff236fd0f3c
Thanks for your time on IRC :)
