### ISSUE TITLE
Why do you use reflection ?

### ISSUE THREAD

**Issue by lyrixx** [TheFootballSocialClub/FSCHateoasBundle#61]
here: https://github.com/TheFootballSocialClub/FSCHateoasBundle/blob/master/Serializer/Handler/PagerfantaHandler.php#L61-L66

I did not understand the code.

you can do:

``` php
$visitor->setDefaultRootName('collection');
$visitor->document = $visitor->createDocument();
```

Obviously, you want to call the root name `collection`

And, If you really want to check, could you open a PR on the serializer. reflection is so slow ... :(

**Comment by adrienbrault** [comment]
I the user already set the default root name, I don't want to override it, but yep, I'll open a pr
