### ISSUE TITLE
Using jms/serializer 1.13.*

### ISSUE THREAD

**Issue by empire** [TheFootballSocialClub/FSCHateoasBundle#63]
Hi @adrienbrault,
First, thanks for your work on this helpful bundle, Is it possible to use jms/serializer 1.13.\* instead of 1.12.*.
Thanks

**Comment by adrienbrault** [comment]
Hi @empire, you can now update to the 0.5 version of the bundle to be able to use a newer version of the serializer!

**Comment by empire** [comment]
Thanks @adrienbrault
