### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by sprain** [TheFootballSocialClub/FSCHateoasBundle#69]
We realized we are having performance issues because of this bundle. If we remove the `@Rest\Relation` annotations from our entities (about 4-6 per entity) we can cut our reponse times in half! (From 0.6s to 0.3s)

**Comment by sprain** [comment]
To be more precise: It is `@Rest\Route` causing the slow down.

**Comment by adrienbrault** [comment]
Do you have the same issue with yaml configuration ?

**Comment by adrienbrault** [comment]
Is it as slow with 1 annotation per entity as with 10 annotations ?

**Comment by sprain** [comment]
Thanks for your replies.

Some first insights:
- Using `BazingaHateoasBundle` made no difference.
- There is no difference whether there are 10 or 1 relations. Only 0 relations makes a difference (in our case 0.3s instead of 0.6s response time)
- `@Route` annotation is the cause. Setting simply a string as route makes it pretty much as fast as leaving the relations away.

A different finding:
Using `@Serializer\VirtualProperty` with JMSSerializer also slows things down a lot. However, a combination of the above problems and the virtual property has no additional effect. No relations, no virtual property: 0.3s. Relations, but no virtual property: 0.6s. No relations, virtual properties: 0.6s. Relations and virtual properties: 0.6s.

Will try yaml now and report back.

**Comment by sprain** [comment]
Unfortunately, there is no difference in using yaml instead of annotations.

**Comment by sprain** [comment]
Problem solved!

Well, no. Not solved yet, but it has nothing to do with this bundle. It's caused by a different bundle which replaces the default Symfony2 router.

Thanks for your help anyways!
