### ISSUE TITLE
support adding specific request attributes to the parameters in generateUrl()

### ISSUE THREAD

**Issue by lsmith77** [TheFootballSocialClub/FSCHateoasBundle#9]
i have some examples where I also support setting the `_format` via the URL, so to generate the correct URLs I would need to also have the `_format` request attributed passed to the `generateUrl()` call.

then again do we really want to cover this use case? we can just assume that people are using proper accept header to request the format they want.

furthermore fixing this will require the link classes to gain access to the request instance, which is a bit iffy in general.

**Comment by adrienbrault** [comment]
The route parameters are created from the configuration parameters via https://github.com/TheFootballSocialClub/FSCHateoasBundle/blob/master/Factory/ParametersFactory.php (see the tests https://github.com/TheFootballSocialClub/FSCHateoasBundle/blob/master/Tests/Factory/ParametersFactoryTest.php )

We may allow something like:

```
parameters:
    _format: @_format
```

**Comment by adrienbrault** [comment]
Merged my work into master. You can now add relations at runtime https://github.com/TheFootballSocialClub/FSCHateoasBundle#add-relations-on-objects-at-runtime

**Comment by lsmith77** [comment]
maybe it should also be possible to dynamically add parameters to statically configured relations? this way one could simply dynamically add the `_format` to the parameters in the controller.

**Comment by adrienbrault** [comment]
I wasn't clear, but the last feature I added, let you add metadata to a single instance of a class.

You can already alter class metadata, this way:

``` php
<?php

$classMetadata = $this->get('fsc_hateoas.metadata.base_factory')->getMetadataForClass('Bundle\\Entity\\Root');
foreach ($classMetadata->getRelations() as $relation) {
    if ('users' != $relation->getRel()) {
        continue;
    }

    $relation->setParams(array_merge($relation->getParams(), array(
        'extra_param' => 'yeah!',
    )));
}
```

**Comment by lsmith77** [comment]
not super elegant, but does the trick:
https://github.com/liip/LiipHelloBundle/commit/5e9ae767786c258cec1467e4106d7bc3bfba3e0c#L0R118

but we should maybe think a bit more if we could automate this somehow.
for example i could imagine that maybe the parameter is configured statically, but the request instance must be manually passed in the controller.

**Comment by hutchic** [comment]
Adding my two-cents that this needs a more elegant solution.  In my scenario the version number and authentication token (and optionally _format) are part of the URL being able to substitute those values into the HATEOS links via annotation would be a huge improvement over the current provided solution.

**Comment by adrienbrault** [comment]
@lsmith77 @hutchic Is #12 a good enough solution for you use cases ?

You'd have to create a listeners that would always do:

``` php
$this->get('fsc_hateoas.routing.generator')->setExtraParameters(array(
    '_format' => $request->get('_format'),
    'version' => $request->get('version'),
));
```

And so on

**Comment by lsmith77** [comment]
looks good to me.
